services:

  fights-db:
    image: mongo:7.0
    # container_name: fights-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fights
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - ${PWD}/database/fights-db/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js:ro
  # rest-heroes:
  #   build: 
  #     dockerfile: Dockerfile
  #     target: rest-heroes
  #     context: .
  #   ports:
  #     - "8080:3000"
  # rest-villains:
  #   build: 
  #     dockerfile: Dockerfile
  #     target: rest-villains
  #     context: .
  #   ports:
  #     - "8081:3000"
  # grpc-locations:
  #   build: 
  #     dockerfile: Dockerfile
  #     target: grpc-locations
  #     context: .
  #   ports:
  #     - "50051:50051"
  # rest-fights:
  #   build: 
  #     dockerfile: Dockerfile
  #     target: rest-fights
  #     context: .
  #   ports:
  #     - "8082:3000"
  heroes-db:
    image: postgres:16
    # container_name: heroes-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: heroes_database
    volumes:
      - ${PWD}/database/heroes-db/init/heroes.sql:/docker-entrypoint-initdb.d/init.sql:ro

  villains-db:
    image: postgres:16
    # container_name: villains-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: villains_database
    volumes:
      - ${PWD}/database/villains-db/init/villains.sql:/docker-entrypoint-initdb.d/init.sql:ro
  locations-db:
    image: mariadb:11.5
    # container_name: locations-db
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: locations
      MARIADB_PASSWORD: locations
      MARIADB_DATABASE: locations_database
      MARIADB_ROOT_PASSWORD: locations
      MARIADB_SKIP_TEST_DB: yes
    volumes:
      - ${PWD}/database/locations-db/init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql:ro
  heroes:
    build: 
      context: services/heroes
    environment:
      DATABASE_URL: "postgres://superman:superman@heroes-db:5432/heroes_database"
    ports:
      - "8001:8000"

  villains:
    build: 
      context: services/villains
    environment:
      DATABASE_URL: "postgres://superman:superman@villains-db:5432/villains_database"
    ports:
      - "8002:8000"

  locations:
    build: 
      context: services/locations
    environment:
      MYSQL_URL: "mysql://locations:locations@locations-db/locations_database"
    ports:
      - "8003:8000"

  fights:
    build: 
      context: services/fights
    ports:
      - "8004:8000"
