---
name: Superheroes k6 scenario
author: Frank Lyaruu
description: Superheroes (Rust) k6 load testing scenario )
compose-file: !include compose.yml
services:
    k6:
      build: k6-image
      environment:
        K6_HOST: http://fights:8000 
      command: ["bash", "-c", "while true; do sleep 3600; done"]
      volumes:
        - ./k6:/k6:ro
        - ./k6/results:/results
flow:
  - name: Test Superheroes 1 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=1 /k6/load.js
        note: Starting k6 Load Test 1 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: Test Superheroes 10 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=10 /k6/load.js
        note: Starting k6 Load Test 10 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: Test Superheroes 50 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=50 /k6/load.js
        note: Starting k6 Load Test 50 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true        
      # - type: console
      #   command: sleep 30
      #   note: Idling
